Migrated to Minecraft version 1.20.5
axieum/authme pull request #113
Opened 2024-04-23 19:55 UTC by TeddyBear2004

Currently the IntelliJ Configuration 'Minecraft Client' does not work on the branch, because 'fabric-screen-api-v1 2.0.15+6f7ba8f23b' contains a mixin that is faulty due to the update. However, one built by 'gradlew build' works.

2024-04-24 03:20 UTC, axieum requested changes
Love this, thank you! Just a few minor tweaks if you have time. :)

2024-04-24 03:20 UTC, axieum commented on gradle.properties
> +mod_version = 8.0.0+1.20.5
```suggestion
mod_version = 8.0.0+1.20.4
```
We'll let the CI pipeline update the version. :)

2024-04-24 03:20 UTC, axieum commented on gradle.properties
> +yarn_mappings=1.20.5+build.1
```suggestion
yarn_mappings = 1.20.5+build.1
```

2024-04-24 03:20 UTC, axieum commented on gradle.properties
> +mr_game_versions = 1.20.3, 1.20.4, 1.20.5
```suggestion
mr_game_versions = 1.20.5
```

2024-04-24 03:20 UTC, axieum commented on build.gradle
> +    sourceCompatibility = targetCompatibility = JavaVersion.VERSION_21
Let's update the CI/CD pipeline to use Java 21 too please.
https://github.com/axieum/authme/blob/1ad64813853d0badce50215ec400ed65734e8450/.github/workflows/build.yml#L26-L30
https://github.com/axieum/authme/blob/1ad64813853d0badce50215ec400ed65734e8450/.github/workflows/release.yml#L47-L51

2024-04-24 05:06 UTC, axieum commented
> Here are the changes, But I still need to work on the GUI: ![image](https://private-user-images.githubusercontent.com/56771258/325084676-a0be3b90-62db-4582-82ef-d7f655923138.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MzU0NjQsIm5iZiI6MTcxMzkzNTE2NCwicGF0aCI6Ii81Njc3MTI1OC8zMjUwODQ2NzYtYTBiZTNiOTAtNjJkYi00NTgyLTgyZWYtZDdmNjU1OTIzMTM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA1MDYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMjYzNGFjZDhhZTgwMjZjNjk4NDRmNzg2MGM4ODYyZTlhMWQwNTk4ZDU0ZDg1OTQ5YzhlZTU2YjJlNzI1YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gWbxmkPs6zXKOc17HgrDVFGuCu_-JxbGsdnUb4XNSh0)

Oh wow, yeah okay, that is interesting. I suppose we need to render the text after the new blur is applied hahahaha.

2024-04-24 08:17 UTC, TeddyBear2004 commented
Got it up and running.

2024-04-27 07:20 UTC, axieum commented
Thanks. I haven't forgotten about this one, just getting up and running on my local soon.

2024-04-28 04:36 UTC, axieum approved these changes

2024-04-28 04:40 UTC, merged